---
#========================
# File fix_chrome_rd.yml
#
# Description: Fix chrome remote desktop when it gets messed up
#
# Author: Derek 'dRock' Halsey
#========================

- name: Remove Chrome and Chrome Remote Desktop
  hosts: "{{ variable_host }}"
  gather_facts: false
  tags:
  - remove
  tasks:

  - name: APT | Uninstall packages
    become: true
    become_user: root
    apt:
      name: "{{ item }}"
      state: absent
      purge: true
    with_items:
    - google-chrome-stable
    - chrome-remote-desktop

  - name: File | remove apt sources
    become: true
    become_user: root
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - /etc/apt/sources.list.d/google-chrome.list
    - /etc/apt/sources.list.d/chromeos.list
    - /etc/apt/sources.list.d/chrome-remote-desktop.list
    - /opt/google/chrome-remote-desktop/chrome-remote-desktop

  - name: SHELL | reboot the system
    become: true
    become_user: root
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0

  - name: WAIT_FOR | Wait for ssh to resume
    local_action:
      module: wait_for
      port: 22
      host: "{{ host.fqdn }}"
      delay: 30
      timeout: 400

- name: Apply transcoder role
  hosts: "{{ variable_host }}"
  gather_facts: true
  roles: [ transcoder ]
  tags:
  - transcoder

- name: Reboot one more time
  hosts: "{{ variable_host }}"
  gather_facts: false
  tags:
  - reboot
  tasks:

  - name: SHELL | reboot the system
    become: true
    become_user: root
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0

  - name: WAIT_FOR | Wait for ssh to resume
    local_action:
      module: wait_for
      port: 22
      host: "{{ host.fqdn }}"
      delay: 30
      timeout: 400