---
#========================
# File hyper_v_clustered_instance.yml
#
# Description: Creates a VM on the failover cluster
#
# Author: Derek 'dRock' Halsey
#========================

- name: PLAYBOOK | newUbuntuServer - create a new Ubuntu Server on the Hyper-V host
  hosts: "{{ variable_host }}"
  connection: local
  gather_facts: false
  roles:
  - hyper_v_clustered_instance