---
#========================
# File dark_server.yml
#
# Description: Creates a dark server on the failover cluster
#
# Author: Derek 'dRock' Halsey
#========================

- name: Create the Cluster VM
  hosts: "{{ variable_host }}"
  connection: local
  gather_facts: false
  roles:
  - hyper_v_clustered_instance
  tags:
  - spawn

- name: Initial Ububtu Configuration
  hosts: "{{ variable_host }}"
  gather_facts: false
  roles:
  - linux_setup
  - ubuntuUpdate
  - ubuntu_cifs_client
  tags:
  - initalConfig

- name: Initial Ububtu Configuration
  hosts: "{{ variable_host }}"
  gather_facts: true
  roles:
  - ubuntu_desktop
  - transcoder
    transcoder:
      user: "{{ ansible_user }}"
      fqdn: "{{ host.fqdn }}"
  tags:
  - transcoder
