---
#========================
# File ubuntu_server.yml
#
# Description: Creates a base Ubuntu Server
#
# Author: Derek 'dRock' Halsey
#========================

- name: Ensure VM exsits
  hosts: "{{ variable_host }}"
  connection: local
  gather_facts: false
  roles:
  - hyper_v_clustered_instance
  tags:
  - spawn

- name: Initial Ububtu Configuration
  hosts: "{{ variable_host }}"
  gather_facts: false
  roles:
  - linux_setup
  - ubuntuUpdate
  - ubuntu_cifs_client
  tags:
  - initalConfig